apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-2
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pvala/gitops-manifest-repo.git
    targetRevision: release
    path: hello-app-2/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true