apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/pvala/gitops-manifest-repo.git
    targetRevision: HEAD
    path: hello-app-3/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true